service: textractor

frameworkVersion: "4"

custom:
  stage: ${opt:stage, 'development'}
  pythonRequirements:
    fileName: requirements.txt
    dockerizePip: linux
    no-deploy:
      - boto3
      - botocore
    layer:
      name: textractor-${self:custom.stage}-python-requirements
      compatibleRuntimes:
        - python3.12
    useDownloadCache: false
    useStaticCache: false
    slim: true

    slimPatternsAppendDefaults: false
    slimPatterns:
      - "/*.py[c|o]"
      - "/pycache*"

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  profile: dev-textractor
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - textract:DetectDocumentText
          Resource: "*"
      managedPolicies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      assumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
      - "application/octet-stream"
      - "application/pdf"

functions:
  app:
    name: ${self:service}-${self:custom.stage}-app
    handler: main.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer

    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /upload
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Forwarded-For
              - X-Forwarded-Port
              - Accept
              - Origin
              - Referer
              - User-Agent
            allowCredentials: false
      - http:
          path: /{proxy+}
          method: any
          cors: true

package:
  individually: false
  include:
    - main.py
  exclude:
    - requirements.txt
    - "**/__pycache__/**"
    - "**/*.pyc"
    - .venv/**
    - node_modules/**
    - .DS_Store
    - .serverless/**
    - .idea/**
    - README.md
    - .env.*

plugins:
  - serverless-python-requirements
